title: Charles Petajan Living Textbook
description: A collection of skills and content knowledge
theme: just-the-docs

color_scheme: dark

includes_dir: _includes

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/images/logo.png"
favicon_ico: "/images/icon.ico"
